server:
  port: 8888

# spring.application.name=jpaadv
spring:
  application:
    name: jpaadv
  # ?? ???? 'dev'? ??????
  # -> spring.profiles.active=* ?? ???? ?? ???? (??????? ????)
  profiles:
    #    active: dev
    active: prod

  # JPA -> ?? ??
  jpa:
    show-sql: true
    # ???? jpa ???? ???? sql? ??? ????
    properties:
      # jpa ???
      hibernate:
        # ?? ?? sql ???, ????, ?? ?? ????
        format_sql: true
    # ??? ?? ??
    hibernate:
      ddl-auto: create

  # ????
  thymeleaf:
    cache: false
# ??
output:
  ansi:
    enabled: ALWAYS